apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: elasticsearch
    chart: elasticsearch-1.26.1
    component: client
    heritage: Tiller
    release: elasticsearch
  name: elasticsearch-client
  selfLink: /api/v1/namespaces/logging/services/elasticsearch-client
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: http
  selector:
    app: elasticsearch
    component: client
    release: elasticsearch
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
