apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: elasticsearch
    chart: elasticsearch-1.26.1
    component: master
    heritage: Tiller
    release: elasticsearch
  name: elasticsearch-discovery
  selfLink: /api/v1/namespaces/logging/services/elasticsearch-discovery
spec:
  clusterIP: None
  ports:
  - port: 9300
    protocol: TCP
    targetPort: transport
  selector:
    app: elasticsearch
    component: master
    release: elasticsearch
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
