apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  labels:
    app: tomcat
spec:
  selector:
    app: tomcat
  ports:
  - name: tomcat
    port: 80
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      name: tomcat
      labels:
        app: tomcat
    spec:
      restartPolicy: Always
      containers:
      - image: tomcat:8.5-alpine
        imagePullPolicy: IfNotPresent
        name: tomcat
        volumeMounts: 
        - name: nfs-pvc
          mountPath: /var/log
        ports:
        - name: tomcat
          containerPort: 8080
      volumes:
      - name: nfs-pvc
        persistentVolumeClaim:
          claimName: nfs-pvc
