apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      name: tomcat
      labels:
        app: tomcat
    spec:
      containers:
      - image: tomcat:8.5-alpine
        imagePullPolicy: IfNotPresent
        name: tomcat
        ports:
        - name: tomcat
          containerPort: 8080
