apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tomcat-ingress
  namespace: default
  labels:
    app: tomcat-ingress
  annotations: 
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: tomcat.test.com
    http:
      paths:
      - backend:
          serviceName: tomcat-svc
          servicePort: 80
        path: /
