apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
  namespace: monitoring
spec:
  alerting:
    alertmanagers:
    - name: alertmanager-main
      namespace: monitoring
      port: web
  baseImage: deploy.bocloud/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 2
  retention: 180 #配置日志保留时间
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: k8s
      role: alert-rules
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: v2.4.3
  volumes:
  - name: prometheus-vol
    persistentVolumeClaim:
      claimName: efk-storage  #指定挂载的storageclass名称
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: efk-storage
        accessModes: 
        - ReadWriteOnce
        resources:
          requests:
            storage: 250Gi