apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv1
  namespace: logging
spec:
  capacity:
    storage: 30Gi
  accessModes: ["ReadWriteMany","ReadOnlyMany","ReadWriteOnce"] 
  nfs:
    path: /nfs/es1
    server: master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv2
  namespace: logging
spec:
  capacity:
    storage: 30Gi
  accessModes: ["ReadWriteMany","ReadOnlyMany","ReadWriteOnce"] 
  nfs:
    path: /nfs/es2
    server: master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv3
  namespace: logging
spec:
  capacity:
    storage: 4Gi
  accessModes: ["ReadWriteMany","ReadOnlyMany","ReadWriteOnce"] 
  nfs:
    path: /nfs/es3
    server: master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv4
  namespace: logging
spec:
  capacity:
    storage: 4Gi
  accessModes: ["ReadWriteMany","ReadOnlyMany","ReadWriteOnce"]
  nfs:
    path: /nfs/es4
    server: master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv5
  namespace: logging
spec:
  capacity:
    storage: 30Gi
  accessModes: ["ReadWriteMany","ReadOnlyMany","ReadWriteOnce"]
  nfs:
    path: /nfs/es5
    server: master
