apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-01
  namespace: default
spec:
  capacity:
    storage: 5Gi
  accessModes: ["ReadWriteMany","ReadOnlyMany","ReadWriteOnce"] 
  nfs:
    path: /data/volumes/v1
    server: master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-02
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes: ["ReadWriteMany","ReadOnlyMany","ReadWriteOnce"] 
  nfs:
    path: /data/volumes/v2
    server: master
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-03
  namespace: default
spec:
  capacity:
    storage: 2Gi
  accessModes: ["ReadWriteMany","ReadOnlyMany","ReadWriteOnce"]
  nfs:
    path: /data/volumes/v3
    server: master
