apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv
  namespace: kube-system
spec:
  capacity:
    storage: 2Gi
  accessModes: ["ReadWriteMany","ReadOnlyMany","ReadWriteOnce"] 
  nfs:
    path: /data/volumes/alertmanager
    server: 192.168.4.23
