apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: user01-binding
subjects:
- kind: User
  name: user01
  apiGroup: "" 
roleRef:
  apiGroup: ""
  kind: Role
  name: user01-role
