apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-20191028
  labels:
    type: from-storageclass
    namespace: default
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
