apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-20191120
  labels:
    type: from-storageclass
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Mi
