apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test-20191028
  namespace: default
spec:
  accessModes: ["ReadWriteMany","ReadOnlyMany","ReadWriteOnce"]
  storageClassName: nfs-client
  persistentVolumeReclaimPolicy: Recycle
  resources:
    requests:
      storage: 100Mi