apiVersion: v1
kind: Service
metadata:
  name: baidu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80

---
apiVersion: v1
kind: Endpoints
metadata:
  name: baidu
subsets:
  - addresses:
      - ip: "180.97.33.108"
    ports:
      - port: 80
