apiVersion: v1
kind: Pod
metadata:
  name: readiess-probe-httpget-pod
  namespace: default
spec:
  containers:
  - name: http
    image: nginx:latest
    ports:
    - name: http
      containerPort: 80
    readinessProbe:
      httpGet:
        port: http
        path: /index.html
      initialDelaySeconds: 2
      periodSeconds: 3
