apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: ikubernetes/myapp:v1
    ports:
    - name: http
      containerPort: 80
    imagePullPolicy: IfNotPresent
  restartPolicy: OnFailure

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: default
spec:
  clusterIP: 10.99.99.99
  selector:
    app: nginx
  ports:
  - name: http-nginx
    port: 80
    nodePort: 30080
    targetPort: 80
  type: NodePort
  sessionAffinity: None
