apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"tomcat"},"name":"tomcat-svc","namespace":"default"},"spec":{"ports":[{"name":"tomcat","port":80,"targetPort":8080}],"selector":{"app":"tomcat"}}}
  creationTimestamp: null
  labels:
    app: tomcat
  name: tomcat-svc
  selfLink: /api/v1/namespaces/default/services/tomcat-svc
spec:
  ports:
  - name: tomcat
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: tomcat
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
