apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: kube-system
  labels:
    type: prometheus
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 30Gi
