apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-slave-pvc
  namespace: default
  labels:
    type: redis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
