apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: default
spec:
  capacity:
    storage: 8Gi
  accessModes: ["ReadWriteMany","ReadOnlyMany","ReadWriteOnce"] 
  nfs:
    path: /data/volumes/redis
    server: 192.168.4.23
